# 虛擬環境名稱 ##################################################################
name: ${MY_VIRTUAL_ENV_NAME}
# name: my_env

# 【頻道清單】套件下載時，依照下面順序來使用哪個通道的優先選擇############################
channels:
  - defaults
  - conda-forge

#【安裝需求套件】 #################################################################
#說明：
#dependencies: 
# ==>透過 conda 方式安裝
#  - <套件名稱>
#  - <套件名稱>=<版本號碼>
#  - <套件名稱>=<版本號碼>=<編譯版本>
# ...
#  - pip: ==>透過 pip 方式安裝
#      - <pip套件名稱>
#      - <pip套件名稱>==<版本號碼>
dependencies:
# 1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣1️⃣
# 透過 conda 方式安裝packages
# for common packages ---------------------------------------------------------
  - python=${MY_PYTHON_VERSION}
  # - python=3.10.15
  - pip
# for YYYY packages ---------------------------------------------------------
  # - TA-Lib=0.6.4
# for ZZZZ packages ---------------------------------------------------------
# 2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣2️⃣
# 透過 pip 方式安裝packages
  - pip:
    # - vnpy_ctastrategy
    # - black
    # - flake8
    # - numpy==2.2.6
    # 安裝vnpy相關子套件會自動加入基本的vnpy套件
# for YYYY packages ---------------------------------------------------------
# for ZZZZ packages ---------------------------------------------------------
###############################################################################
# https://github.com/vnpy/vnpy
# https://github.com/ta-lib/ta-lib-python
# miniconda + node.js 
# ==> https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-miniconda/.devcontainer/Dockerfile
